#!/bin/sh
missing() {
	if ! which $1 > /dev/null 2>&1
	then
		echo "Missing $2 dependency" >&2
		exit 1
	fi
}
missing tsc typescript
missing npx npm
missing entr entr

echo "./build: Check/install rollup"
npx rollup -v

echo "./build: Initial TS compilation"
tsc

echo "./build: Initial rollup bundling"
npx rollup -c rollup.config.mjs

echo "./build: Incremental, ongoing TS compilation"
tsc -w &

echo "./build: rollup watching of out-ts/ with entr"
find out-ts/* -type f | entr npx rollup -c rollup.config.mjs

# However, since find doesn't update, you'll have to restart this build script if
# you add a new file to look for changes in. I think it's possible to set up a
# loop that checks the whole directory but that's probably more resource-intensive.
